# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chat_pb2 as chat__pb2


class ChatAppStub(object):
    """The definition of the service performed by Server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PerformService = channel.unary_unary(
                '/chat.ChatApp/PerformService',
                request_serializer=chat__pb2.ServerRequest.SerializeToString,
                response_deserializer=chat__pb2.ServerReply.FromString,
                )


class ChatAppServicer(object):
    """The definition of the service performed by Server
    """

    def PerformService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatAppServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PerformService': grpc.unary_unary_rpc_method_handler(
                    servicer.PerformService,
                    request_deserializer=chat__pb2.ServerRequest.FromString,
                    response_serializer=chat__pb2.ServerReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.ChatApp', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatApp(object):
    """The definition of the service performed by Server
    """

    @staticmethod
    def PerformService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.ChatApp/PerformService',
            chat__pb2.ServerRequest.SerializeToString,
            chat__pb2.ServerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
